/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as RitualsRouteImport } from './routes/rituals'
import { Route as RitualRouteImport } from './routes/ritual'
import { Route as PerfumeOilsRouteImport } from './routes/perfume-oils'
import { Route as NourishingBodyOilRouteImport } from './routes/nourishing-body-oil'
import { Route as MoistureRouteImport } from './routes/moisture'
import { Route as DryBodyOilRouteImport } from './routes/dry-body-oil'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BodyWashRouteImport } from './routes/body-wash'
import { Route as BodyOilRouteImport } from './routes/body-oil'
import { Route as BodyLotionRouteImport } from './routes/body-lotion'
import { Route as BodyButterRouteImport } from './routes/body-butter'
import { Route as BodyRouteImport } from './routes/body'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopProductIdRouteImport } from './routes/shop.$productId'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const RitualsRoute = RitualsRouteImport.update({
  id: '/rituals',
  path: '/rituals',
  getParentRoute: () => rootRouteImport,
} as any)
const RitualRoute = RitualRouteImport.update({
  id: '/ritual',
  path: '/ritual',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfumeOilsRoute = PerfumeOilsRouteImport.update({
  id: '/perfume-oils',
  path: '/perfume-oils',
  getParentRoute: () => rootRouteImport,
} as any)
const NourishingBodyOilRoute = NourishingBodyOilRouteImport.update({
  id: '/nourishing-body-oil',
  path: '/nourishing-body-oil',
  getParentRoute: () => rootRouteImport,
} as any)
const MoistureRoute = MoistureRouteImport.update({
  id: '/moisture',
  path: '/moisture',
  getParentRoute: () => rootRouteImport,
} as any)
const DryBodyOilRoute = DryBodyOilRouteImport.update({
  id: '/dry-body-oil',
  path: '/dry-body-oil',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BodyWashRoute = BodyWashRouteImport.update({
  id: '/body-wash',
  path: '/body-wash',
  getParentRoute: () => rootRouteImport,
} as any)
const BodyOilRoute = BodyOilRouteImport.update({
  id: '/body-oil',
  path: '/body-oil',
  getParentRoute: () => rootRouteImport,
} as any)
const BodyLotionRoute = BodyLotionRouteImport.update({
  id: '/body-lotion',
  path: '/body-lotion',
  getParentRoute: () => rootRouteImport,
} as any)
const BodyButterRoute = BodyButterRouteImport.update({
  id: '/body-butter',
  path: '/body-butter',
  getParentRoute: () => rootRouteImport,
} as any)
const BodyRoute = BodyRouteImport.update({
  id: '/body',
  path: '/body',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopProductIdRoute = ShopProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ShopRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/body': typeof BodyRoute
  '/body-butter': typeof BodyButterRoute
  '/body-lotion': typeof BodyLotionRoute
  '/body-oil': typeof BodyOilRoute
  '/body-wash': typeof BodyWashRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/dry-body-oil': typeof DryBodyOilRoute
  '/moisture': typeof MoistureRoute
  '/nourishing-body-oil': typeof NourishingBodyOilRoute
  '/perfume-oils': typeof PerfumeOilsRoute
  '/ritual': typeof RitualRoute
  '/rituals': typeof RitualsRoute
  '/shop': typeof ShopRouteWithChildren
  '/shop/$productId': typeof ShopProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/body': typeof BodyRoute
  '/body-butter': typeof BodyButterRoute
  '/body-lotion': typeof BodyLotionRoute
  '/body-oil': typeof BodyOilRoute
  '/body-wash': typeof BodyWashRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/dry-body-oil': typeof DryBodyOilRoute
  '/moisture': typeof MoistureRoute
  '/nourishing-body-oil': typeof NourishingBodyOilRoute
  '/perfume-oils': typeof PerfumeOilsRoute
  '/ritual': typeof RitualRoute
  '/rituals': typeof RitualsRoute
  '/shop': typeof ShopRouteWithChildren
  '/shop/$productId': typeof ShopProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/body': typeof BodyRoute
  '/body-butter': typeof BodyButterRoute
  '/body-lotion': typeof BodyLotionRoute
  '/body-oil': typeof BodyOilRoute
  '/body-wash': typeof BodyWashRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/dry-body-oil': typeof DryBodyOilRoute
  '/moisture': typeof MoistureRoute
  '/nourishing-body-oil': typeof NourishingBodyOilRoute
  '/perfume-oils': typeof PerfumeOilsRoute
  '/ritual': typeof RitualRoute
  '/rituals': typeof RitualsRoute
  '/shop': typeof ShopRouteWithChildren
  '/shop/$productId': typeof ShopProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/body'
    | '/body-butter'
    | '/body-lotion'
    | '/body-oil'
    | '/body-wash'
    | '/checkout'
    | '/contact'
    | '/dry-body-oil'
    | '/moisture'
    | '/nourishing-body-oil'
    | '/perfume-oils'
    | '/ritual'
    | '/rituals'
    | '/shop'
    | '/shop/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/body'
    | '/body-butter'
    | '/body-lotion'
    | '/body-oil'
    | '/body-wash'
    | '/checkout'
    | '/contact'
    | '/dry-body-oil'
    | '/moisture'
    | '/nourishing-body-oil'
    | '/perfume-oils'
    | '/ritual'
    | '/rituals'
    | '/shop'
    | '/shop/$productId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/body'
    | '/body-butter'
    | '/body-lotion'
    | '/body-oil'
    | '/body-wash'
    | '/checkout'
    | '/contact'
    | '/dry-body-oil'
    | '/moisture'
    | '/nourishing-body-oil'
    | '/perfume-oils'
    | '/ritual'
    | '/rituals'
    | '/shop'
    | '/shop/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BodyRoute: typeof BodyRoute
  BodyButterRoute: typeof BodyButterRoute
  BodyLotionRoute: typeof BodyLotionRoute
  BodyOilRoute: typeof BodyOilRoute
  BodyWashRoute: typeof BodyWashRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  DryBodyOilRoute: typeof DryBodyOilRoute
  MoistureRoute: typeof MoistureRoute
  NourishingBodyOilRoute: typeof NourishingBodyOilRoute
  PerfumeOilsRoute: typeof PerfumeOilsRoute
  RitualRoute: typeof RitualRoute
  RitualsRoute: typeof RitualsRoute
  ShopRoute: typeof ShopRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rituals': {
      id: '/rituals'
      path: '/rituals'
      fullPath: '/rituals'
      preLoaderRoute: typeof RitualsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ritual': {
      id: '/ritual'
      path: '/ritual'
      fullPath: '/ritual'
      preLoaderRoute: typeof RitualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfume-oils': {
      id: '/perfume-oils'
      path: '/perfume-oils'
      fullPath: '/perfume-oils'
      preLoaderRoute: typeof PerfumeOilsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nourishing-body-oil': {
      id: '/nourishing-body-oil'
      path: '/nourishing-body-oil'
      fullPath: '/nourishing-body-oil'
      preLoaderRoute: typeof NourishingBodyOilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moisture': {
      id: '/moisture'
      path: '/moisture'
      fullPath: '/moisture'
      preLoaderRoute: typeof MoistureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dry-body-oil': {
      id: '/dry-body-oil'
      path: '/dry-body-oil'
      fullPath: '/dry-body-oil'
      preLoaderRoute: typeof DryBodyOilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/body-wash': {
      id: '/body-wash'
      path: '/body-wash'
      fullPath: '/body-wash'
      preLoaderRoute: typeof BodyWashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/body-oil': {
      id: '/body-oil'
      path: '/body-oil'
      fullPath: '/body-oil'
      preLoaderRoute: typeof BodyOilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/body-lotion': {
      id: '/body-lotion'
      path: '/body-lotion'
      fullPath: '/body-lotion'
      preLoaderRoute: typeof BodyLotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/body-butter': {
      id: '/body-butter'
      path: '/body-butter'
      fullPath: '/body-butter'
      preLoaderRoute: typeof BodyButterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/body': {
      id: '/body'
      path: '/body'
      fullPath: '/body'
      preLoaderRoute: typeof BodyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$productId': {
      id: '/shop/$productId'
      path: '/$productId'
      fullPath: '/shop/$productId'
      preLoaderRoute: typeof ShopProductIdRouteImport
      parentRoute: typeof ShopRoute
    }
  }
}

interface ShopRouteChildren {
  ShopProductIdRoute: typeof ShopProductIdRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopProductIdRoute: ShopProductIdRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BodyRoute: BodyRoute,
  BodyButterRoute: BodyButterRoute,
  BodyLotionRoute: BodyLotionRoute,
  BodyOilRoute: BodyOilRoute,
  BodyWashRoute: BodyWashRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  DryBodyOilRoute: DryBodyOilRoute,
  MoistureRoute: MoistureRoute,
  NourishingBodyOilRoute: NourishingBodyOilRoute,
  PerfumeOilsRoute: PerfumeOilsRoute,
  RitualRoute: RitualRoute,
  RitualsRoute: RitualsRoute,
  ShopRoute: ShopRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
